### ISSUE TITLE
using GPU

### ISSUE THREAD

**Issue by sbassi** [maxbachmann/Levenshtein#18]
Is there a way to make this program to use a GPU?

**Comment by maxbachmann** [comment]
No, as of now, there is no option to run any of the algorithms on a GPU. Since most algorithms use bitparallelism it would theoretically be possible to implement them on a GPU. However at least right now I consider this out of scope of RapidFuzz/Levenshtein. It would be a lot of work to implement and a lot harder to distribute. So this would likely need to be implemented in a separate library.

I assume you're asking because you need to compare a lot of string. Did you already try to use `rapidfuzz.cdist` for this? It allows comparing whole lists of strings, which is significantly faster, since it removes the overhead of calling the functions from Python. In addition it gives the option to use multithreading:
```
from rapidfuzz import process, string_metric

cdist(a, b, scorer=string_metric.levenshtein)
```
