### ISSUE TITLE
Distance Normalization

### ISSUE THREAD

**Issue by kjijakli** [maxbachmann/Levenshtein#40]
Hi

How is the distance normalized in Levenshtein.ratio(s1, s2)? It'll be helpful if you can provide the formula. 

Thanks

**Comment by maxbachmann** [comment]
`Levenshtein.ratio` is a normalized version of the InDel similarity, which is a modified version of the Levenshtein distance which only allows Insertions + Deletions (or in terms of the Levenshtein distance gives Substitutions a weight of 2).

It uses the following steps for the calculation:
```python
indel_dist = indel_distance(s1, s2)
norm_indel_dist = indel_dist / (len(s1) + len(s2))
norm_indel_sim = 1.0 - norm_indel_dist
```

It is unclear why the original author considered this a good idea, since this difference in algorithm between `Levenshtein.distance` and `Levenshtein.ratio` is very surprising for most users.

In case you actually want the normalized Levenshtein similarity, you can use:
```python
from rapidfuzz.distance import Levenshtein
Levenshtein.normalized_similarity(s1, s2)
```
instead

**Comment by kjijakli** [comment]
Thank you so much!
